# Project information
site_name: Daves Docs
docs_dir: docs

# Repository
repo_name: opengisch/quick-md-docs
repo_url: https://github.com/opengisch/ch.sob.lksob.perimeter-manager
edit_uri: https://github.com/opengisch/ch.sob.lksob.perimeter-manager/tree/master/docs/

# Theme configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - search.suggest
    - search.highlight
  logo: assets/lksob-perimeter-manager-icon.svg
  favicon: assets/lksob-perimeter-manager-icon.svg
  icon:
    logo: assets/lksob-perimeter-manager-icon.svg
  palette:
    - scheme: default
      primary: green
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: green
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
        primary: white

# Page tree
nav:
  - Versatzproblem bei CadastraSymbol Fonts in QGIS: versatz.md

markdown_extensions:
  - attr_list
  - def_list
  - admonition

plugins:
  - exporter:
      formats:
        pdf:
          enabled: true
          stylesheets:
            - resources/stylesheets/pdf.scss
          covers:
            front: resources/templates/covers/front.html.j2
          aggregator:
            enabled: true
            output: documentation.pdf
            covers: front
          browser:
            debug: false
  - macros:
      on_undefined: strict
